using System.Collections.Generic;
using NUnit.Framework;
using PolygonArsenal;
using UnityEditor;
using UnityEngine;

// EditMode tests for the projectile visuals generated by ProjectileVisualsBuilder
public class ProjectileVisualsTests
{
    private const string EffectFolder = "Assets/Prefabs/Effects";
    private const string ProjectileFolder = "Assets/Prefabs/Projectiles";
    private const string LitSmokeMaterialPath = "Assets/Polygon Arsenal/Materials/Main/PolyLitSurface.mat";

    // Modules that keep the tower's look on purpose: the Hangar's squadron path (more fighters is its look),
    // the Mine Factory's salvage path (economy only), the cluster rockets and the pulse (their own base look)
    private static readonly Dictionary<string, string[]> WithoutVisual = new Dictionary<string, string[]>
    {
        { "Bomb Tower", new[] { "p2t3" } },
        { "Bullet Dispenser Tower", new[] { "p2t3", "p3t3" } },
        { "Hangar Tower", new[] { "p1t1", "p1t2", "p1t3" } },
        { "Mine Factory", new[] { "p3t1", "p3t2", "p3t3" } },
    };

    private static readonly string[] Towers =
    {
        "Default Tower", "Bomb Tower", "Bullet Dispenser Tower", "Hangar Tower", "Beam Tower", "Sniper Tower", "Mine Factory",
    };

    private static IEnumerable<GameObject> Prefabs(string folder)
    {
        foreach (string guid in AssetDatabase.FindAssets("t:Prefab", new[] { folder }))
            yield return AssetDatabase.LoadAssetAtPath<GameObject>(AssetDatabase.GUIDToAssetPath(guid));
    }

    [Test]
    public void EveryUpgradeModuleHasItsLook()
    {
        foreach (string name in Towers)
        {
            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/Tower/" + name + ".prefab");
            Assert.IsNotNull(prefab, name);
            UpgradePath[] paths = prefab.GetComponent<UpgradeManager>().GetUpgradePaths();
            WithoutVisual.TryGetValue(name, out string[] exempt);
            for (int p = 0; p < paths.Length; p++)
            {
                for (int t = 0; t < paths[p].UpgradeModules.Length; t++)
                {
                    string key = "p" + (p + 1) + "t" + (t + 1);
                    if (exempt != null && System.Array.IndexOf(exempt, key) >= 0)
                        continue;
                    SerializedProperty upgrades = new SerializedObject(prefab.GetComponent<UpgradeManager>())
                        .FindProperty("upgradePaths").GetArrayElementAtIndex(p)
                        .FindPropertyRelative("upgradeModules").GetArrayElementAtIndex(t).FindPropertyRelative("upgrades");
                    bool found = false;
                    for (int i = 0; i < upgrades.arraySize; i++)
                        found |= upgrades.GetArrayElementAtIndex(i).objectReferenceValue is VisualUpgrade;
                    Assert.IsTrue(found, name + " " + key + " has no VisualUpgrade");
                }
            }

            foreach (VisualUpgrade visual in prefab.GetComponents<VisualUpgrade>())
            {
                SerializedProperty entries = new SerializedObject(visual).FindProperty("entries");
                for (int i = 0; i < entries.arraySize; i++)
                    Assert.IsNotNull(entries.GetArrayElementAtIndex(i).FindPropertyRelative("prefab").objectReferenceValue, name + ": empty visual slot");
            }
        }
    }

    // Opaque lit smoke puffs block the view; the generated effects turn them into fading wisps
    [Test]
    public void GeneratedEffectsHaveNoOpaqueSmoke()
    {
        Material lit = AssetDatabase.LoadAssetAtPath<Material>(LitSmokeMaterialPath);
        int count = 0;
        foreach (GameObject effect in Prefabs(EffectFolder))
        {
            count++;
            foreach (ParticleSystemRenderer renderer in effect.GetComponentsInChildren<ParticleSystemRenderer>(true))
                Assert.IsFalse(System.Array.IndexOf(renderer.sharedMaterials, lit) >= 0, effect.name + "/" + renderer.name + " still uses lit smoke");
        }
        Assert.Greater(count, 50);
    }

    // Visual copies of the projectile wrappers must hit like their source (same kind and hit shape)
    [Test]
    public void ProjectileCopiesKeepTheirHitShape()
    {
        string[] sources = { "ProjectileParent", "ProjectileParentRound", "ProjectileParentBomb", "ProjectileParentBombClustering", "ProjectileParentPulse", "GrenadeBlueOBJ" };
        Dictionary<string, ProjectileArchetype> byScript = new Dictionary<string, ProjectileArchetype>();
        foreach (string source in sources)
        {
            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/" + source + ".prefab");
            byScript[Signature(prefab)] = ProjectileArchetype.Get(prefab);
        }

        int count = 0;
        foreach (GameObject copy in Prefabs(ProjectileFolder))
        {
            count++;
            ProjectileArchetype archetype = ProjectileArchetype.Get(copy);
            Assert.IsTrue(byScript.TryGetValue(Signature(copy), out ProjectileArchetype source), copy.name + ": no matching wrapper");
            Assert.AreEqual(source.Kind, archetype.Kind, copy.name);
            Assert.AreEqual(source.HitRadius, archetype.HitRadius, 1e-5f, copy.name);
            Assert.AreEqual(source.HitHalfLength, archetype.HitHalfLength, 1e-5f, copy.name);
            Assert.IsNotNull(copy.GetComponent<PolygonProjectileScript>(), copy.name);
        }
        Assert.Greater(count, 8);
    }

    // The wrappers differ by their projectile component (and the cluster rocket by its bomblets)
    private static string Signature(GameObject prefab)
    {
        string kind = prefab.GetComponent<Clusterbomb>() != null ? "cluster"
            : prefab.GetComponent<ProjectilePulse>() != null ? "pulse"
            : prefab.GetComponent<ProjectileBomb>() is ProjectileBomb bomb ? (bomb.ClusterProjectilePrefab != null ? "clusterRocket" : "rocket")
            : prefab.GetComponent<ProjectileBasic>() != null ? "basic" : "round";
        return kind;
    }

    [Test]
    public void HighestPriorityWinsEachSlot()
    {
        GameObject host = new GameObject("visuals");
        try
        {
            GameObject a = new GameObject("a"), b = new GameObject("b"), c = new GameObject("c");
            VisualUpgrade low = Make(host, 11, (VisualSlot.Flight, a), (VisualSlot.Impact, a));
            VisualUpgrade high = Make(host, 31, (VisualSlot.Flight, b));
            VisualUpgrade middle = Make(host, 22, (VisualSlot.Impact, c));

            TowerVisuals visuals = new TowerVisuals();
            visuals.Add(high);
            visuals.Add(low);
            visuals.Add(middle);
            Assert.AreSame(b, visuals.Resolve(VisualSlot.Flight, null));
            Assert.AreSame(c, visuals.Resolve(VisualSlot.Impact, null));
            Assert.IsNull(visuals.Resolve(VisualSlot.Muzzle, null));
            Assert.AreSame(low, visuals[0]);
            Assert.AreSame(high, visuals[2]);

            int version = visuals.Version;
            visuals.Remove(high);
            Assert.AreNotEqual(version, visuals.Version);
            Assert.AreSame(a, visuals.Resolve(VisualSlot.Flight, null));
            Object.DestroyImmediate(a);
            Object.DestroyImmediate(b);
            Object.DestroyImmediate(c);
        }
        finally
        {
            Object.DestroyImmediate(host);
        }
    }

    private static VisualUpgrade Make(GameObject host, int priority, params (VisualSlot slot, GameObject prefab)[] entries)
    {
        VisualUpgrade upgrade = host.AddComponent<VisualUpgrade>();
        SerializedObject data = new SerializedObject(upgrade);
        data.FindProperty("priority").intValue = priority;
        SerializedProperty list = data.FindProperty("entries");
        list.arraySize = entries.Length;
        for (int i = 0; i < entries.Length; i++)
        {
            list.GetArrayElementAtIndex(i).FindPropertyRelative("slot").intValue = (int)entries[i].slot;
            list.GetArrayElementAtIndex(i).FindPropertyRelative("prefab").objectReferenceValue = entries[i].prefab;
        }
        data.ApplyModifiedPropertiesWithoutUndo();
        return upgrade;
    }
}
