using System;
using UnityEngine;

// Gives an upgrade module its own look: replaces the prefabs a tower's weapons fire or play (see VisualSlot).
// Purely cosmetic, the stats stay with the module's StatUpgrades. Generated by ProjectileVisualsBuilder:
// priority = tier * 10 + path, so the furthest tier decides a slot that several paths set.
public class VisualUpgrade : Upgrade
{
    [Serializable]
    public struct Entry
    {
        public VisualSlot slot;
        public GameObject prefab;
    }

    [SerializeField] private int priority;
    [SerializeField] private Entry[] entries = Array.Empty<Entry>();

    public int Priority => priority;

    public GameObject Get(VisualSlot slot)
    {
        if (entries == null)
            return null;
        for (int i = 0; i < entries.Length; i++)
        {
            if (entries[i].slot == slot && entries[i].prefab != null)
                return entries[i].prefab;
        }
        return null;
    }

    public override void ApplyUpgrade(StatsManager statsManager)
    {
        if (statsManager.TryGetComponent(out Tower tower))
            tower.Visuals.Add(this);
    }

    public override void RemoveUpgrade(StatsManager statsManager)
    {
        if (statsManager.TryGetComponent(out Tower tower))
            tower.Visuals.Remove(this);
    }
}
